Annotation.create!([
  {author_id: 2, step_id: 2, body: "hello"}
])
Recipe.create!([
  {author_id: 4, title: "Vegetarian Chili", ingredients: "1 tablespoon olive oil \n1/2 medium onion, chopped \n2 bay leaves \n1 teaspoon ground cumin \n2 tablespoons dried oregano \n1 tablespoon salt \n2 stalks celery, chopped \n2 green bell peppers, chopped \n2 jalapeno peppers, chopped \n3 cloves garlic, chopped \n2 (4 ounce) cans chopped green chile peppers, drained \n2 (12 ounce) packages vegetarian burger crumbles \n3 (28 ounce) cans whole peeled tomatoes, crushed \n1/4 cup chili powder \n1 tablespoon ground black pepper \n1 (15 ounce) can kidney beans, drained \n1 (15 ounce) can garbanzo beans, drained \n1 (15 ounce) can black beans \n1 (15 ounce) can whole kernel corn", image_url: "vnsxfa0twrigcjonzqgr", description: "Just because it’s veggie doesn’t mean it lacks flavor! This chili packs a ton of flavor and spice into a nutritious dish that will satisfy for your whole family. It also keeps for up to a week, so it’s great for on-the-go types who need to cook lunches for the whole week in advance. Enjoy!"},
  {author_id: 1, title: "Sour Cream Cornbread With Aleppo", ingredients: "1 cup (125 grams) all-purpose flour\n1 cup (145 grams) yellow cornmeal\n2 tablespoon (25 grams) granulated sugar\n2 teaspoons baking powder\n1 teaspoon dried aleppo flakes\n1/2 teaspoon table salt\n1 large egg, lightly beaten\n1 cup sour cream\n1/3 cup buttermilk\n2 tablespoons olive oil", image_url: "dwfolszdsrjeeabhoxz1", description: "A savory, slightly spicy take on classic cornbread inspired by Smitten Kitchen. Aleppo is a Turkish pepper flake - in a pinch, you can substitute regular red paper flakes, though be careful things don’t get too hot!"},
  {author_id: 4, title: "Tomato Soup", ingredients: "1 medium white or yellow onion \n6 tablespoons (3/4 stick) butter \nTwo 14.5-ounce cans diced tomatoes \nOne 46-ounce bottle or can tomato juice \n3 to 6 tablespoons sugar \n1 or 2 tablespoons chicken base, or 3 chicken bouillon cubes \nFreshly ground black pepper \n1 cup sherry, optional \n1 1/2 cups heavy cream \n1/4 cup chopped fresh basil \n1/4 cup chopped flat-leaf parsley", image_url: "rh5zggfknv6lutzldlx8", description: "Warm and creamy, this is the perfect start for a fall or winter feast."},
  {author_id: 2, title: "Kugel", ingredients: "1 (8 ounce) package large egg noodles \n6 tablespoons butter, sliced \n6 eggs, separated \n1/2 cup white sugar \n3/4 (8 ounce) package cream cheese, softened \n4 tablespoons sour cream \n1 (16 ounce) package cottage cheese, creamed \n1 pinch salt \n4 tablespoons butter, melted \n1/4 cup white sugar \n1/3 cup graham cracker crumbs", image_url: "paea26zzrnmxqilqpvwy", description: "Kugel is a traditional Jewish dish most often eaten at Saturday lunches or on holidays. It can be sweet or savory, though this version is a bit of both. It would be hard to argue that kugel is particularly healthy, but it’s so delicious that it’s best not to think too hard about that!"},
  {author_id: 1, title: "Fish-Fragrant Eggplant", ingredients: "1 1/4 lbs (600g) eggplant \nSalt \nCooking oil, for deep-frying (1 1/2 cups plus 2 tablespoons/400ml will do if you are using a round-bottomed wok) \n1 1/2 tablespoons Sichuanese chilli bean paste, or Sichuan pickled chilli paste, or a mixture of the two\n1 tablespoon finely chopped ginger \n1 tablespoon finely chopped garlic \n2/3 cup (150ml) chicken stock \n2 teaspoons sugar \n3/4 teaspoon potato flour mixed with one tablespoon cold water \n2 teaspoons Chinkiang vinegar \n4 tablespoons finely sliced spring onion greens", image_url: "fish_fragrant_eggplant_ncakrj", description: "This is a classic Sichuan-style Chinese eggplant dish. The name is a little strange, as there is no actual fish (or fish favor!) in it, but it will appeal to eggplant and garlic lovers alike."},
  {author_id: 3, title: "Vanilla Ice Cream", ingredients: "3 cups half-and-half\n1 cup heavy cream \n8 large egg yolks \n9 ounces vanilla sugar \n2 teaspoons pure vanilla extract", image_url: "antg0v8cz5mbdwdquz1s", description: "Vanilla ice cream is such a classic treat that it needs no real explanation. This version comes to us from Food Network’s Alton Brown."},
  {author_id: 3, title: "Chinese Scallion Pancakes", ingredients: "4 cups flour, plus more \n1 tbsp. baking powder \n1 tbsp. kosher salt \n1⁄3 cup canola oil \n2 tbsp. toasted sesame oil \n1 1⁄2 cups thinly sliced scallions \n1 tsp. crushed red chile flakes \n1⁄2 tsp. ground white pepper", image_url: "fjgtt6nt5kgvri84qhas", description: "These scallion pancakes, called cong you bing (literally “scallion and oil pastries”) are ubiquitous in the Chinese-speaking world. Perhaps most often eaten a quick breakfast snack, they go well as a side with anything or as a treat on their own."},
  {author_id: 2, title: "Sweet Potato Wedges", ingredients: "1/2 cup, plus 2 tablespoons butter \n1 1/2 teaspoons ground cinnamon \n4 sweet potatoes, scrubbed and cut lengthwise into wedges \n2 teaspoons salt \n2 teaspoons freshly ground black pepper", image_url: "fpj1zzwgoz0sa7tjfs9s", description: "Sweet potatoes are usually a pretty easy go-to healthy choice, unless, as is the case here, they’re featured in a recipe created by Paula Deen. But hey, when they taste so good, who’s complaining?"},
  {author_id: 1, title: "Carrot Cake", ingredients: "4 eggs\n1 1/4 cups vegetable oil\n2 cups white sugar\n2 teaspoons vanilla extract\n2 cups all-purpose flour\n2 teaspoons baking soda\n2 teaspoons baking powder\n1/2 teaspoon salt\n2 teaspoons ground cinnamon\n3 cups grated carrots\n1 cup chopped pecans\n1/2 cup butter, softened\n8 ounces cream cheese, softened\n4 cups confectioners' sugar\n1 teaspoon vanilla extract\n1 cup chopped pecans", image_url: "xdp27twkti6sizcymmg5", description: "Everybody loves carrot cake. What other dessert pumps you full of good ol’ fat and sugar while simultaneously giving you super enhanced night vision capabilities? Jokes aside, this recipe is fantastic. Just be careful not to overdo it on the sugar here."}
])
Step.create!([
  {recipe_id: 1, display_idx: 0, body: "Cut the eggplant lengthways into three thick slices, then cut these into evenly sized batons. Sprinkle them with salt, mix well and leave in a colander for at least 30 minutes to drain. "},
  {recipe_id: 1, display_idx: 1, body: "n a wok, heat the oil for deep-frying to 350°F (180˚C). Add the eggplant in batches and deep-fry for three to four minutes until slightly golden on the outside and soft and buttery within. Remove and drain on paper towels."},
  {recipe_id: 1, display_idx: 2, body: "Drain the deep-frying oil, rinse the wok if necessary, then return it to a medium flame. When the wok is hot again, add 3 tbsp of oil. Add the chilli bean paste and stir-fry until the oil is red and fragrant, then add the ginger and garlic and continue to stir-fry until you can smell their aromas. Take care not to burn these seasonings; remove the wok from the heat for a few seconds if necessary to control the temperature (you want a gentle, coaxing sizzle, not a scorching heat)."},
  {recipe_id: 1, display_idx: 3, body: "Add the stock and sugar and mix well. Season with salt to taste if necessary. Add the fried eggplant to the sauce and let them simmer gently for a minute or so to absorb some of the flavors. Then stir the potato flour mixture, pour it over the eggplant and stir in gently to thicken the sauce. Add the vinegar and spring onions and stir a few times, then serve."},
  {recipe_id: 2, display_idx: 0, body: "Preheat the oven to 400 °F. Generously butter a 9×5-inch loaf pan, or coat it with a nonstick spray."},
  {recipe_id: 2, display_idx: 1, body: "Whisk flour, cornmeal, sugar, baking powder, aleppo and salt together in a large bowl. In a smaller bowl, whisk together the egg, sour cream, buttermilk and olive oil."},
  {recipe_id: 2, display_idx: 2, body: "Stir the wet ingredients into the dry ones, mixing until just barely combined."},
  {recipe_id: 2, display_idx: 3, body: "Spread the batter in your prepared and bake for 22 to 25 minutes. A toothpick inserted into the center should come out clean."},
  {recipe_id: 2, display_idx: 4, body: "Serve in slices, toasted with honey butter or salted and honeyed brown butter."},
  {recipe_id: 3, display_idx: 0, body: "Preheat oven to 350 degrees F (175 degrees C). Grease a 9x13 inch glass baking dish."},
  {recipe_id: 3, display_idx: 1, body: "Bring a large pot of lightly salted water to a boil. Add pasta and cook for 8 to 10 minutes or until al dente; drain and stir in 6 tablespoons sliced butter."},
  {recipe_id: 3, display_idx: 2, body: "In a medium bowl beat egg yolks with sugar and cream cheese; stir into noodles and add sour cream, cottage cheese and salt. Beat egg whites until stiff and fold into mixture. Transfer mixture to prepared dish."},
  {recipe_id: 3, display_idx: 3, body: "n a small bowl combine melted butter, 1/4 cup sugar, and graham cracker crumbs. Sprinkle over noodle mixture."},
  {recipe_id: 3, display_idx: 4, body: "Bake in preheated oven for 1 hour. Can be served hot or cold, preferably in small squares."},
  {recipe_id: 4, display_idx: 0, body: "Place the half-and-half and the heavy cream into a medium saucepan, over medium heat. Bring the mixture just to a simmer, stirring occasionally, and remove from the heat."},
  {recipe_id: 4, display_idx: 1, body: "In a medium mixing bowl whisk the egg yolks until they lighten in color. Gradually add the sugar and whisk to combine. Temper the cream mixture into the eggs and sugar by gradually adding small amounts, until about a third of the cream mixture has been added. Pour in the remainder and return the entire mixture to the saucepan and place over low heat. Continue to cook, stirring frequently, until the mixture thickens slightly and coats the back of a spoon and reaches 170 to 175 degrees F. "},
  {recipe_id: 4, display_idx: 2, body: "Pour the mixture into a container and allow to sit at room temperature for 30 minutes. Stir in the vanilla extract."},
  {recipe_id: 4, display_idx: 3, body: "Place the mixture into the refrigerator and once it is cool enough not to form condensation on the lid, cover and store for 4 to 8 hours or until the temperature reaches 40 degrees F or below."},
  {recipe_id: 5, display_idx: 0, body: "Process 2 cups flour and baking powder in a food processor. With motor running, add 2⁄3 cup cold water; process until dough forms, about 40 seconds. Transfer to a plate; set aside. Add remaining flour and salt to food processor, and with motor running, add 2⁄3 cup boiling water; process until dough forms, about 30 seconds. Return reserved dough to food processor; pulse until both doughs come together, about 35 seconds. Transfer to a lightly floured work surface; knead until smooth, about 4 minutes. Transfer to a greased bowl, cover; let sit at room temperature for 2 hours."},
  {recipe_id: 5, display_idx: 1, body: "Halve dough; using a rolling pin, roll 1 dough half into a 10\" x 20\" rectangle. Brush with 1 tbsp. canola oil and half the sesame oil. Sprinkle with half the scallions, half the chile flakes, and half the white pepper. Beginning with one long side, tightly roll dough like a jelly roll. Cut roll crosswise into 3 pieces, slightly stretch each piece, and starting from one edge, coil piece horizontally, tucking the end underneath. Using your hand, gently flatten coil into a disk; using a rolling pin, flatten into a 5\" circle. Repeat with remaining pieces and second dough half, 1 tbsp. canola oil, remaining sesame oil, scallions, chile flakes, and white pepper. Let pancakes sit for about 10 minutes."},
  {recipe_id: 5, display_idx: 2, body: "Heat oven to 200°. Heat 2 tsp. canola oil in a 10\" nonstick skillet over medium heat. Add 1 pancake to skillet; cook, swirling skillet and turning once, until golden and crisp, about 10 minutes. Transfer to a baking sheet; place in oven to keep warm. Repeat with remaining oil and pancakes; cut into wedges to serve."},
  {recipe_id: 6, display_idx: 0, body: "Preheat the oven to 400 degrees F. "},
  {recipe_id: 6, display_idx: 1, body: "In a large saucepan over medium-high heat, melt the butter. Remove the pot from the heat and stir in the cinnamon. Add the potato wedges to the butter and toss to combine. Season the potatoes with the salt and pepper."},
  {recipe_id: 6, display_idx: 2, body: "Spread the potatoes in an even layer on a baking sheet. Roast the potatoes, stirring occasionally, until tender, about 20 to 25 minutes. Remove from the oven to a serving dish and serve."},
  {recipe_id: 7, display_idx: 0, body: "Preheat oven to 350 degrees F (175 degrees C). Grease and flour a 9x13 inch pan. "},
  {recipe_id: 7, display_idx: 1, body: "In a large bowl, beat together eggs, oil, white sugar and 2 teaspoons vanilla. Mix in flour, baking soda, baking powder, salt and cinnamon. Stir in carrots. Fold in pecans. Pour into prepared pan."},
  {recipe_id: 7, display_idx: 2, body: "Bake in the preheated oven for 40 to 50 minutes, or until a toothpick inserted into the center of the cake comes out clean. Let cool in pan for 10 minutes, then turn out onto a wire rack and cool completely."},
  {recipe_id: 7, display_idx: 3, body: "To Make Frosting: In a medium bowl, combine butter, cream cheese, confectioners' sugar and 1 teaspoon vanilla. Beat until the mixture is smooth and creamy. Stir in chopped pecans. Frost the cooled cake."},
  {recipe_id: 8, display_idx: 0, body: "Heat the olive oil in a large pot over medium heat. Stir in the onion, and season with bay leaves, cumin, oregano, and salt. Cook and stir until onion is tender, then mix in the celery, green bell peppers, jalapeno peppers, garlic, and green chile peppers. When vegetables are heated through, mix in the vegetarian burger crumbles. Reduce heat to low, cover pot, and simmer 5 minutes."},
  {recipe_id: 8, display_idx: 1, body: "Mix the tomatoes into the pot. Season chili with chili powder and pepper. Stir in the kidney beans, garbanzo beans, and black beans. Bring to a boil, reduce heat to low, and simmer 45 minutes. Stir in the corn, and continue cooking 5 minutes before serving."},
  {recipe_id: 9, display_idx: 0, body: "To begin, dice the onion. Melt the butter in a large pot or Dutch oven. Throw in the onion and cook until translucent."},
  {recipe_id: 9, display_idx: 1, body: "Now dump in the diced tomatoes and stir to combine. Add the tomato juice. "},
  {recipe_id: 9, display_idx: 2, body: "Next - and this is important - in order to combat the acidity of the tomatoes add 3 to 6 tablespoons of sugar. Now, you'll want to start on the low side, then taste and add more as needed. Some tomatoes and juice have more of an acidic bite than others. (For what it's worth, and I realize it's not worth much, I use 6 tablespoons of sugar.) "},
  {recipe_id: 9, display_idx: 3, body: "Next, add 1 or 2 tablespoons chicken base to the pot. I added 3, and it wound up being a little too much. "},
  {recipe_id: 9, display_idx: 4, body: "Now you can add lots of freshly ground black pepper. Stir to combine, then heat almost to a boil. Then turn off the heat. "},
  {recipe_id: 9, display_idx: 5, body: "Add in the sherry if desired. Stir in the cream. Add the basil and parsley and stir. "},
  {recipe_id: 9, display_idx: 6, body: "Serve the soup warm!"}
])
User.create!([
  {username: "johnnycakes", password_digest: "$2a$10$goguNfDd3K9g.4Mxl6t45e992VpZLNyUU4Y.4V2EnBoLwwc35PzRa", session_token: "GQ6vJqiPx2teu_4RkPbiHw"},
  {username: "hannah", password_digest: "$2a$10$lwT4HtIVABrxePh7edYlQucjInKlWBiPYHu/J.1G/KZBrD/ZVnO6y", session_token: "gkb5vNhaNrmxSEp9DNLnzQ"},
  {username: "samuel", password_digest: "$2a$10$c/./tXGozw8vlUEx.6IB0.fcBopIke/ozhAtoxdOxNhhBEQBKAj82", session_token: "74YPs_sAk4J3C1JPUsAntg"},
  {username: "arturo", password_digest: "$2a$10$wRZB4jPLrAWhhzwLWtAa4O.0bWlDdmjGsd10Dth4tlB5u1eZZncJa", session_token: "YL3xaDpGIvd4omPZQ54cmg"}
])
